### ISSUE TITLE
Serialization of EventHandlers

### ISSUE THREAD

**Issue by nordic81** [tomba/netserializer#27]
I think I’ve found a bug in your netserializer:

The serializer tries to serialize EventHandlers, which aren’t serializable and shouldn’t be serialized at all. Since it’s obviously not marked as NotSerialized (and the NonSerialized-Attribute can’t be set on EventHandlers), EvenHandlers cause an exception.

I think it would be appropriate to exempt evenhandlers from the fieldinfos for serialization.

**Comment by tomba** [comment]
I take it you are seeing the "Cannot serialize {0}: ISerializable not supported" exception?

Actually Delegates are serializable (MulticastDelegates, to be exact), but only via the ISerializable interface. NetSerializer doesn't support ISerializables.

And you can add [NonSerialized] to fields which contain delegates. But it's true that if you use "event" to define an event handler, you can't set it as nonserialized.

So... I'm not sure what to do. It's trivial to add a line to skip Delegates:

```
diff --git a/NetSerializer/Helpers.cs b/NetSerializer/Helpers.cs
index f9f4583..f209e43 100644
--- a/NetSerializer/Helpers.cs
+++ b/NetSerializer/Helpers.cs
@@ -25,6 +25,7 @@ namespace NetSerializer

                        var fields = type.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance                                .Where(fi => (fi.Attributes & FieldAttributes.NotSerialized) == 0)
+                               .Where(fi => !fi.FieldType.IsSubclassOf(typeof(Delegate)))
                                .OrderBy(f => f.Name, StringComparer.Ordinal);
```

But that prevents anyone from writing a custom serializer for his delegates... I don't know why anyone would want to serialize delegates, though, but who knows...

Did you try writing a custom serializer, that doesn't do anything, just catches Delegates?

**Comment by nordic81** [comment]
Yes, that's exactly the exception I get.

To the question concerning serializing delegates:
I already read several articles about why it would be extremely unwise to do so and i don't know of any serializer which serializes events by default.

If you still want to provide the possibility to serialize delegates, you could use the Type.GetEvents-Method to filter out the events only.

Another idea would be to provide some way of configuring the serializer so that delegates and/or events won't be serialized

Currently I implemented a custom serializer that doesn't do anything as a work around. It works, but I would call it a code smell...

**Comment by tomba** [comment]
I think any serializer that supports ISerializable will serialize delegates automatically. Whether that's wise, well, I wouldn't do that, at least for the use cases for which NetSerializer was made.

I think it's better to skip delegates. Are you able to test the modification to NetSerializer in my earlier reply?

**Comment by nordic81** [comment]
I just tested your modifications and they work fine.

Wouldn't it be be better to be a bit more restrictive regarding EventHandlers?

```
var fields = type.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly)
                .Where(fi => (fi.Attributes & FieldAttributes.NotSerialized) == 0)
                .Where(fi => !(fi.FieldType == typeof(EventHandler)))
                .Where(fi => !(fi.FieldType.IsGenericType && fi.FieldType.GetGenericTypeDefinition() == typeof(EventHandler<>)))
                .OrderBy(f => f.Name, StringComparer.Ordinal);
```

**Comment by tomba** [comment]
Hmm, why? EventHandlers are delegates. Isn't it better to just filter out all delegates?

Or the other way: if other delegates are allowed to be serialized (with a custom serializer), then why not EventHandlers?

**Comment by nordic81** [comment]
Hmmm... you've definitely got a point there.

And even though the semantics of events make it feel kinda "wrong" to me to serialize events, I still can think of a scenario where one would want to serialize events

**Comment by tomba** [comment]
I've been thinking about this, and I don't like adding an exclusion rule for Delegate (or EventHandler) types. 

- As a rule of thumb, you shouldn't have Delegates in the types you serialize with NetSerializer in the first place. NetSerializer is a specialized serializer and the types should be designed to be serialized.

- If there was an exclusion rule, and you had Delegates in the types you serialize, the Delegate fields would not get serialized. In the receiving end this would show up as the Delegates being null, which I think is not the correct behavior from the serializer. Either the fields should get serialized properly, or the serializer should give an error.

- In the odd case that you actually want to serialize the Delegate, an exclusion rule would prevent you from doing that with a custom TypeSerializer.

I think a NoOpSerializer class shipped with NetSerializer solves this quite fine. If you do have classes with Delegates (or any other types that cannot be serialized), it will be easy to add exclusions for those types:

`new Serializer(types, new NoOpSerializer(new[] { typeof(Delegate) }, true) });`

The 'true' parameter is used to tell that all subclasses of Delegate (say, Action<int>) are handled by NoOpSerializer, instead of plain Delegate class.

How does this sound?

**Comment by nordic81** [comment]
Sounds pretty good. This would preserve the high level of flexibility and would allow serializing delegates as well as events while handing a simple solution to those who don't want to serialize delegates/events.

btw: should I supply you with a HashSet-Serializer?

**Comment by tomba** [comment]
v4.0 has NoOpSerializer, so closing this.

Yes, you can send your HashSet serializer for review. Although I'm not sure if that fits in to the NetSerializer's minimalistic approach.
